### ISSUE TITLE
Database Opening/Closing Issue #AppCrashing

### ISSUE THREAD

**Issue by tsinghal** [tsinghal/Focus#16]
This happens when i try to open schedules and press back at a decent pace. From Schedules Activity.

<img width="1045" alt="screen shot 2017-10-23 at 10 54 47 am" src="https://user-images.githubusercontent.com/16664647/31904652-ba57b9d0-b7e0-11e7-88aa-281a45da7453.png">
<img width="1005" alt="screen shot 2017-10-23 at 10 54 53 am" src="https://user-images.githubusercontent.com/16664647/31904653-ba7cff1a-b7e0-11e7-9eca-966a8fba8282.png">
<img width="922" alt="screen shot 2017-10-23 at 10 55 00 am" src="https://user-images.githubusercontent.com/16664647/31904654-baa36772-b7e0-11e7-839b-b0711e7de409.png">

**Comment by prateekbhatia** [comment]
Try it again, let me know if the error persists!
